# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
#fastlane_version "1.49.0"

default_platform :ios


platform :ios do
#before_all do
#cocoapods
#end

desc "Run tests"
lane :test do
scan(
scheme: "BabySitterKata",
project: "BabySitterKata.xcodeproj",
clean: true,
code_coverage: true,
skip_slack: true,
sdk: "iphonesimulator9.3",
destination: "name=iPhone 6"
)
end

desc "Calculate test code coverage score. Need to run test beforehand."
lane :report_test_coverage do
xcov(
project: "BabySitterKata.xcodeproj",
scheme: "BabySitterKata",
output_directory: "xcov_output"
)
end


end
